name: 'cord_bi'
version: '1.0.0'
config-version: 2

profile: 'cord_bi'

model-paths: ['models']
analysis-paths: ['analysis']
macro-paths: ['macros']
test-paths: ['tests']
seed-paths: ['seeds']
snapshot-paths: ['snapshots']

clean-targets: ['target', 'dbt_packages']

models:
  cord_bi:
    staging:
      +materialized: view
      +schema: staging
